export const payloadWarmup = {
    minItems: [
        [
            {
                id: "OB",
                stats: {
                    vitality: 350,
                    strength: 70,
                    intelligence: 70,
                    wisdom: 40,
                    ap: 1,
                    range: 1,
                    neutralDamage: 10,
                    earthDamage: 10,
                    fireDamage: 10,
                    prospecting: 15,
                    waterResistPer: 10,
                    dodge: 6,
                    criticalDamage: 25,
                    pods: 350,
                    initiative: 140,
                    apReduction: 4,
                    apResist: 4,
                    mpReduction: 4,
                    mpResist: 4,
                },
                panoplies: ["6u"],
            },
            {
                id: "On",
                stats: {
                    vitality: 400,
                    wisdom: 50,
                    power: 50,
                    ap: 1,
                    earthDamage: 10,
                    fireDamage: 10,
                    waterDamage: 10,
                    airDamage: 10,
                    prospecting: 10,
                    waterResistPer: 10,
                    lock: 20,
                    pushbackResist: 20,
                    apReduction: 5,
                    apResist: 5,
                    mpReduction: 5,
                    mpResist: 5,
                },
                panoplies: ["6h"],
            },
        ],
        [
            {
                id: "Om+Ne",
                stats: {
                    vitality: 400,
                    wisdom: 60,
                    power: 40,
                    earthDamage: 10,
                    fireDamage: 17,
                    waterDamage: 10,
                    airDamage: 17,
                    prospecting: 10,
                    earthResistPer: 10,
                    lock: 9,
                    pushbackResist: 10,
                    apReduction: 6,
                    apResist: 6,
                    mpReduction: 6,
                    mpResist: 3,
                    intelligence: 60,
                    agility: 60,
                    criticalChance: 6,
                    range: 1,
                    summon: 1,
                    waterResistPer: 8,
                    earthResist: 10,
                    airResist: 10,
                    criticalDamage: 12,
                    dodge: 6,
                    initiative: 120,
                },
                panoplies: ["6h", "5Z"],
            },
        ],
        [
            {
                id: "OD",
                stats: {
                    vitality: 350,
                    strength: 70,
                    intelligence: 70,
                    wisdom: 40,
                    criticalChance: 3,
                    summon: 1,
                    neutralDamage: 15,
                    earthDamage: 15,
                    fireDamage: 15,
                    neutralResistPer: 7,
                    earthResistPer: 10,
                    dodge: 10,
                    pods: 350,
                    initiative: 140,
                    apReduction: 4,
                    apResist: 4,
                    mpReduction: 4,
                    mpResist: 4,
                },
                panoplies: ["6u"],
            },
            {
                id: "Op",
                stats: {
                    vitality: 500,
                    wisdom: 40,
                    power: 50,
                    earthDamage: 12,
                    fireDamage: 12,
                    waterDamage: 12,
                    airDamage: 12,
                    prospecting: 15,
                    initiative: 400,
                    neutralResistPer: 10,
                    lock: 20,
                    pushbackResist: 15,
                    apReduction: 4,
                    apResist: 4,
                    mpReduction: 4,
                    mpResist: 4,
                },
                panoplies: ["6h"],
            },
            {
                id: "Nf",
                stats: {
                    vitality: 150,
                    intelligence: 60,
                    agility: 60,
                    wisdom: 50,
                    criticalChance: 7,
                    range: 1,
                    fireDamage: 10,
                    airDamage: 10,
                    heal: 8,
                    prospecting: 10,
                    initiative: 620,
                    earthResistPer: 8,
                    airResistPer: 8,
                    waterResist: 12,
                    lock: -1,
                    mpResist: 1,
                    criticalDamage: 15,
                    dodge: 6,
                    apReduction: 5,
                    apResist: 5,
                    mpReduction: 5,
                },
                panoplies: ["5Z"],
            },
        ],
        [
            {
                id: "Ol",
                stats: {
                    vitality: 500,
                    wisdom: 40,
                    power: 50,
                    summon: 1,
                    earthDamage: 10,
                    fireDamage: 10,
                    waterDamage: 10,
                    airDamage: 10,
                    prospecting: 15,
                    initiative: 600,
                    airResistPer: 10,
                    lock: 15,
                    pushbackResist: 25,
                    apReduction: 4,
                    apResist: 4,
                    mpReduction: 4,
                    mpResist: 4,
                },
                panoplies: ["6h"],
            },
        ],
        [
            {
                id: "OC",
                stats: {
                    vitality: 350,
                    strength: 60,
                    intelligence: 60,
                    wisdom: 40,
                    range: 1,
                    neutralDamage: 10,
                    earthDamage: 10,
                    fireDamage: 10,
                    prospecting: 15,
                    fireResistPer: 15,
                    dodge: 10,
                    criticalDamage: 25,
                    pods: 300,
                    initiative: 120,
                    apReduction: 4,
                    apResist: 4,
                    mpReduction: 4,
                    mpResist: 4,
                },
                panoplies: ["6u"],
            },
            {
                id: "O2",
                stats: {
                    vitality: 350,
                    strength: 70,
                    wisdom: 40,
                    criticalChance: 3,
                    range: 1,
                    neutralDamage: 15,
                    earthDamage: 15,
                    neutralResistPer: 10,
                    earthResistPer: 7,
                    mpReduction: 14,
                    apResist: -1,
                    criticalDamage: 20,
                    pods: 350,
                    initiative: 70,
                    apReduction: 4,
                    mpResist: 4,
                },
                panoplies: ["6r"],
            },
        ],
        [
            {
                id: "Oo",
                stats: {
                    vitality: 400,
                    wisdom: 40,
                    power: 50,
                    mp: 1,
                    earthDamage: 15,
                    fireDamage: 15,
                    waterDamage: 15,
                    airDamage: 15,
                    prospecting: 10,
                    fireResistPer: 10,
                    lock: 10,
                    pushbackResist: 15,
                    apReduction: 4,
                    apResist: 4,
                    mpReduction: 4,
                    mpResist: 4,
                },
                panoplies: ["6h"],
            },
            {
                id: "Nd",
                stats: {
                    vitality: 150,
                    intelligence: 60,
                    agility: 60,
                    wisdom: 50,
                    criticalChance: 6,
                    mp: 1,
                    fireDamage: 8,
                    airDamage: 8,
                    heal: 12,
                    prospecting: 20,
                    neutralResistPer: 7,
                    fireResistPer: 7,
                    lock: 0,
                    mpResist: 1,
                    criticalDamage: 20,
                    pushbackDamage: 15,
                    dodge: 6,
                    initiative: 120,
                    apReduction: 5,
                    apResist: 5,
                    mpReduction: 5,
                },
                panoplies: ["5Z"],
            },
        ],
        [
            {
                id: "LP",
                stats: {
                    vitality: 200,
                    chance: 80,
                    criticalChance: 8,
                    prospecting: 24,
                    criticalDamage: 12,
                    criticalResist: 16,
                    initiative: 80,
                },
                panoplies: [],
            },
        ],
        [
            {
                id: "Oq",
                stats: {
                    vitality: 500,
                    wisdom: 40,
                    power: 50,
                    earthDamage: 12,
                    fireDamage: 12,
                    waterDamage: 12,
                    airDamage: 12,
                    prospecting: 15,
                    neutralResistPer: 3,
                    earthResistPer: 3,
                    fireResistPer: 3,
                    waterResistPer: 3,
                    airResistPer: 3,
                    lock: 15,
                    pushbackResist: 20,
                    apReduction: 4,
                    apResist: 4,
                    mpReduction: 4,
                    mpResist: 4,
                },
                panoplies: ["6h"],
            },
        ],
        [
            {
                id: "6B",
                stats: {
                    criticalChance: 15,
                    criticalDamage: 40,
                },
                panoplies: [],
            },
        ],
        [
            {
                id: "UK",
                stats: {
                    range: -2,
                    criticalDamage: 25,
                },
                panoplies: [],
            },
            {
                id: "GJ+UK",
                stats: {
                    power: 80,
                    range: -2,
                    criticalDamage: 25,
                },
                panoplies: [],
                requirement: {
                    type: "panopliesBonusLessThan",
                    value: 3,
                },
            },
        ],
    ],
    weights: {
        vitality: 0.4,
        ap: 150,
        mp: 130,
        range: 50,
        summon: 30,
        initiative: 0.08,
        wisdom: 2,
        prospecting: 2,
        lock: 3,
        dodge: 3,
        mpReduction: 4,
        apReduction: 4,
        mpResist: 2.5,
        apResist: 2.5,
        heal: 3,
        pods: 0.1,
        strength: 1,
        agility: 1,
        chance: 1,
        intelligence: 1,
        power: 4,
        neutralDamage: 0.1,
        earthDamage: 3,
        fireDamage: 3,
        waterDamage: 3,
        airDamage: 3,
        damage: 12,
        criticalDamage: 5,
        criticalChance: 10,
        pushbackDamage: 3,
        trapDamage: 3,
        trapPower: 1,
        spellDamagePer: 15,
        rangedDamagePer: 15,
        meleeDamagePer: 15,
        weaponDamagePer: 15,
        neutralResistPer: 6,
        earthResistPer: 6,
        fireResistPer: 6,
        waterResistPer: 6,
        airResistPer: 6,
        rangedResistPer: 15,
        meleeResistPer: 15,
        neutralResist: 2,
        earthResist: 2,
        fireResist: 2,
        waterResist: 2,
        airResist: 2,
        criticalResist: 2,
        pushbackResist: 2,
        reflect: 2,
    },
    minStats: {},
    maxStats: {
        ap: 12,
        mp: 6,
        range: 6,
        summon: 6,
        criticalChance: 95,
        neutralResistPer: 50,
        earthResistPer: 50,
        fireResistPer: 50,
        airResistPer: 50,
        waterResistPer: 50,
        rangedResistPer: 50,
        meleeResistPer: 50,
    },
    preStats: {
        vitality: 1050,
        ap: 8,
        mp: 3,
        range: 0,
        summon: 1,
        prospecting: 100,
        pods: 1995,
    },
    panoplies: [
        {
            id: "6u",
            items: ["OB", "OC", "OD"],
            statsWithBonus: [
                {},
                {
                    strength: 40,
                    intelligence: 40,
                    criticalDamage: 40,
                    dodge: 15,
                    pods: 200,
                    initiative: 80,
                },
                {
                    strength: 40,
                    intelligence: 40,
                    criticalDamage: 40,
                    ap: 1,
                    dodge: 15,
                    pods: 200,
                    initiative: 80,
                },
            ],
        },
        {
            id: "6h",
            items: ["Ol", "Om", "On", "Oo", "Op", "Oq"],
            statsWithBonus: [
                {},
                {
                    dodge: -10,
                    initiative: 300,
                    neutralResistPer: 2,
                    fireResistPer: 2,
                    airResistPer: 2,
                    waterResistPer: 2,
                    earthResistPer: 2,
                    rangedResistPer: 3,
                    power: 30,
                    pushbackResist: 10,
                    mpResist: 25,
                    lock: 7,
                },
                {
                    dodge: -20,
                    initiative: 500,
                    neutralResistPer: 4,
                    fireResistPer: 4,
                    airResistPer: 4,
                    waterResistPer: 4,
                    earthResistPer: 4,
                    rangedResistPer: 6,
                    power: 60,
                    pushbackResist: 20,
                    mpResist: 30,
                    lock: 10,
                    ap: 1,
                },
                {
                    ap: 1,
                    lock: 15,
                    mpResist: 50,
                    pushbackResist: 25,
                    power: 100,
                    rangedResistPer: 9,
                    earthResistPer: 6,
                    waterResistPer: 6,
                    airResistPer: 6,
                    fireResistPer: 6,
                    neutralResistPer: 6,
                    initiative: 750,
                    dodge: -25,
                },
                {
                    ap: 1,
                    lock: 20,
                    mpResist: 75,
                    pushbackResist: 35,
                    rangedResistPer: 12,
                    power: 150,
                    earthResistPer: 8,
                    waterResistPer: 8,
                    airResistPer: 8,
                    fireResistPer: 8,
                    neutralResistPer: 8,
                    initiative: 1000,
                    dodge: -35,
                },
                {
                    dodge: -50,
                    rangedResistPer: 15,
                    initiative: 1500,
                    fireResistPer: 10,
                    waterResistPer: 10,
                    airResistPer: 10,
                    earthResistPer: 10,
                    neutralResistPer: 10,
                    power: 200,
                    pushbackResist: 50,
                    mpResist: 100,
                    lock: 30,
                    ap: 2,
                },
            ],
        },
        {
            id: "5Z",
            level: 198,
            items: ["Nd", "Ne", "Nf"],
            statsWithBonus: [
                {},
                {
                    intelligence: 30,
                    agility: 30,
                    criticalDamage: 10,
                    criticalChance: 8,
                    lock: 3,
                    dodge: 3,
                    initiative: 60,
                },
                {
                    ap: 1,
                    criticalDamage: 10,
                    criticalChance: 8,
                    agility: 30,
                    intelligence: 30,
                    lock: 3,
                    dodge: 3,
                    initiative: 60,
                },
            ],
            value: [0, 212.8, 362.8],
        },
        {
            id: "6r",
            level: 200,
            items: ["O1", "O2", "O3"],
            statsWithBonus: [
                {},
                {
                    strength: 60,
                    criticalDamage: 15,
                    criticalChance: 7,
                    pods: 300,
                    initiative: 60,
                },
                {
                    ap: 1,
                    criticalDamage: 15,
                    criticalChance: 7,
                    strength: 60,
                    pods: 300,
                    initiative: 60,
                },
            ],
        },
    ],
};
