export const itemsToSkip = [
    "Amourlette Hernel",
    "Amourlette Hernelle",
    "La Broche Céleste Ankarton",
    "Pagniglou défectueux",
    "Dofus Verdoyant",
    "Alliance",
    "Le Diviseur (MJ)",
    "Bague du hibou",
    "Sacrifice volontaire",
    "Anneau Ocre",
    "Chapeau du Marié",
    "Chapeau de la Mariée",
    "Casque des Mercenaires d'Astrub",
    "Chapeau Tiche troué",
    "Loupe d'improbabilité",
    "Casque isolant",
    "Masque mortuaire",
    "Scaphandre chronomagique",
    "Casque alourdi",
    "Bandeau d'apprenti Pandawushuka",
    "Cape Brâkmarienne",
    "Cape Bontarienne",
    "Cape Banale",
    "Cape des Mercenaires d'Astrub",
    "Bouteille de chronoxygène",
    "Ailes en bois alourdies",
    "Carapace d'entraînement du Maître Torte Hou",
    "Bottananas",
    "Bottes Hoktone usées",
    "Bouclier du Mont Kipou brisé",
    "Bouclier de Sidimote enfoncé",
    "Bouclier des Brigandins écorché",
    "Bouclier du Bûcheron fendu",
    "Ftalmo déchiré",
    "Bouclier Taverne percé",
    "Le Karde Cœur meurtri",
    "Bouclier du Bawbawe explosé",
    "Derma Tho flétri",
    "Bouclier en Mousse cassé",
    "Bouclier Ventaille froissé",
    "Bouclier du Sadida fatigué",
    "Bouclier en Slip sali",
    "Bouclier du Captain Amakna vieilli",
    "Kloume écorné",
    "Bouclier d'Asse évaporé",
    "Bouclier Volant voilé",
    "Bouclier du Chouque sabordé",
    "Bouclier Abraknyde lichené",
    "Bouclier du Bouftou parasité",
    "Bouclier de Bowisse déserté",
    "Bouclier Pandawa bourré",
    "Bouclier du Craqueleur craquelé",
    "Cadran de Feu déréglé",
    "Cadran d'Air déréglé",
    "Cadran de Terre déréglé",
    "Cadran d'Eau déréglé",
    "Bouclier d'entraînement",
    "Bouclier Akwadala englouti",
    "Bouclier Terrdala enterré",
    "Bouclier Feudala brulé",
    "Bouclier Aerdala envolé",
    "Bouclier Fi'Squale cassé",
    "Bouclier de Sidimote cassé",
    "Ftalmo cassé",
    "Bouclier Taverne cassé",
    "Bouclier Akwadala cassé",
    "Bouclier Ventaille cassé",
    "Bouclier du Sadida cassé",
    "Bouclier en Slip cassé",
    "Bouclier d'Asse cassé",
    "Bouclier Abraknyde cassé",
    "Bouclier Pandawa cassé",
    "Cadran de Feu cassé",
    "Cadran d'Air cassé",
    "Cadran de Terre cassé",
    "Cadran d'Eau cassé",
    "Bouclier du Bûcheron cassé",
    "Bouclier du Mont Kipou cassé",
    "Bouclier des Brigandins cassé",
    "Le Karde Cœur cassé",
    "Bouclier du Bawbawe cassé",
    "Derma Tho cassé",
    "Bouclier du Captain Amakna cassé",
    "Kloume cassé",
    "Bouclier Volant cassé",
    "Bouclier du Chouque cassé",
    "Bouclier du Bouftou cassé",
    "Bouclier de Bowisse cassé",
    "Bouclier du Craqueleur cassé",
    "Bouclier Terrdala cassé",
    "Bouclier Feudala cassé",
    "Bouclier Aerdala cassé",
    "Bouclier trophée du Dark Vlad",
    "Bouclier trophée du Moon",
    "Bouclier trophée du Chêne Mou",
    "Bouclier trophée du Dragon Cochon",
    "Bouclier trophée du Minotoror",
    "Bouclier trophée du Kimbo",
    "Bouclier trophée du Wa Wabbit",
    "Bouclier trophée du Koulosse",
    "Bouclier trophée du Sphincter Cell",
    "Bouclier trophée du Bworker",
    "Coupe de Dragokart cassée",
    "Bouclier expérimental en mousse",
    "Bouclier expérimental en laine",
    "Bouclier expérimental en etork",
    "Pandaclier",
    "Ménologium",
    "Ménologium béni",
    "Arc de Chasse",
    "Flûte de Sarr Ys",
    "Baguette Osseuse",
    "Bâton de l'apprenti pélerin",
    "Couteau de Chasse",
    "Épée de Nowel",
    "Épée Langue de Feu",
    "Épée Langue de Feu Réanimée",
    "Épée Nécronyx",
    "Lame de Danaba",
    "Marteau de Percimol ramolli",
    "Marteau d'Ereziah",
    "Marteau de boisaille fortifié",
    "Pelle Hectrochoc",
    "Hache Hémal",
    "Loupe",
    "Flûte",
    "Canne à Koinkoin",
    "Ciseaux à rose démoniaque",
    "Kamapêche",
    "Gants de Mastiqueur",
    "Cracheur du Major Qiu",
    "Attrape-Poussière",
    "Filet de capture de nécrotique",
    "Électrofoudre",
    "Marteau Chronomagique",
    "Pinceau",
    "Pelle du Clan Terra",
    "Baguette de Sourcier bénie",
    "Patatonnerre",
    "Gants Grenne",
    "Baguette de Sourcier",
    "Gants de Zrid",
    "Pioche de Sidoa",
    "Attrape-Cauchemar",
    "Pioche solide",
    "Outil de gravure",
    "Pinceau de calligraphie",
    "Pinceau des serments",
    "Totem de l'équilibre",
    "Attrape-Cauchemar démoniaque",
    "Authentique rouleau d'Ayuto",
    "Croix de Sinane",
    "Balai rudimentaire",
    "Tapette à moskitos",
    "Couteau de chasse de Berb Nhin",
    "Mauvaise Pioche",
    "Pioche Vibrante",
    "Pioche Réquisitionnée",
    "Pioche à usage unique",
    "Petite pierre d'âme parfaite",
    "Moyenne pierre d'âme parfaite",
    "Grande pierre d'âme parfaite",
    "Énorme pierre d'âme parfaite",
    "Gigantesque pierre d'âme parfaite",
    "Gargantuesque pierre d'âme parfaite",
    "Pierre d'âme élémentale",
    "Pierre d'âme parfaite renforcée",
    "Pierre d'âme démoniaque",
    "Filet de capture de Dragodinde",
    "Filet de capture de Muldo",
    "Filet de capture de Volkorne",
    "Peluche-boule : Phorreur",
    "Peluche-boule : Bouftou",
    "Peluche-boule : Tofu",
    "Peluche-boule : Chacha",
    "Peluche-boule : Minikrone",
    "Kwak Oubeh",
    "Chienchiengue",
    "Certificat de Monture",
    "Dragodinde Amande Sauvage",
    "Dragodinde Rousse Sauvage",
    "Dragodinde Dorée Sauvage",
    "Muldo Ebène Sauvage",
    "Muldo Indigo Sauvage",
    "Muldo Orchidée Sauvage",
    "Muldo Pourpre Sauvage",
    "Muldo Doré Sauvage",
    "Volkorne Pourpre sauvage",
    "Volkorne Indigo sauvage",
    "Volkorne Ebène sauvage",
    "Volkorne Orchidée sauvage",
    "Dokoko",
    "Dofus Argenté",
    "Dom de Pin",
];
